const path = require('path');
exports.State = require('./framework/po/State');
exports.Collection = require('./framework/po/Collection');
exports.Component = require('./framework/po/Component');
exports.Page = require('./framework/po/Page');
exports.CredentialManager = require('./framework/credential_manager/CredentialManager');
exports.TaskKiller = require('./framework/taskkiller/TaskKiller');
exports.Memory = require('./framework/memory/Memory');
exports.tasks = require('./gulp/tasks');